version: '3'

services: 
  mysql-service:
    image: 'mysql:5.6'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 944sn3O8d92s
      MYSQL_DATABASE: billmgr
      MYSQL_USER: billmgr
      MYSQL_PASSWORD: 944sn3O8d92s
    volumes:
      - ./mgrdata/db:/var/lib/mysql
    networks:
      static-network:
        ipv4_address: 172.30.20.101

  billmgr-service:
    build: ./billmgr
    hostname: billmanager.docker
    volumes:
      - ./mgrdata/mgr5:/usr/local/mgr5
      - ./cache:/var/cache/yum
    ports:
      - 1500:1500
      - 443:443
    depends_on:
      - mysql-service
    environment:
      BILLMGR_PASSWORD: 944sn3O8d92s
    networks:
      static-network:
        ipv4_address: 172.30.20.100

  website-service:
    image: 'nginx'
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      static-network:
        ipv4_address: 172.30.20.103

  # ipmgr-service:
  #   build: ./ipmgr
  #   hostname: ipmgr.docker
  #   volumes:
  #     - ./mgrdata/mgr5:/usr/local/mgr5
  #   environment:
  #     IPMGR_PASSWORD: 944sn3O8d92s
  #   ports:
  #     - 1501:1500
  #   networks:
  #     static-network:
  #       ipv4_address: 172.30.20.102
  #   depends_on:
  #     - billmgr-service

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.20.0/24