version: '3'

services: 
  mysql-service:
    image: 'mysql:5.6'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 944sn3O8d92s
      MYSQL_DATABASE: billmgr
      MYSQL_USER: billmgr
      MYSQL_PASSWORD: 944sn3O8d92s
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      static-network:
        ipv4_address: 172.30.20.101
    
  billmgr-service:
    build: ./billmgr
    hostname: billmgr.docker
    volumes:
      - ./mgr5:/usr/local/mgr5
    ports:
      - 1500:1500
    depends_on:
      - mysql-service
    networks:
      static-network:
        ipv4_address: 172.30.20.100


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.20.0/24